### ISSUE TITLE
HyperList: The maximum element height 0px has been exceeded; please reduce your item height.

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/hyperlist#21]
Looks like the `getMaxBrowserHeight` function stopped working. I'll investigate, but my guess is something to do with `mergeStyle`.

**Comment by soyuka** [comment]
Yeah I noted this too!

**Comment by tbranyen** [comment]
The error goes away when I switch the code back to:

```
    wrapper.style = 'position: absolute; height: 1px; opacity: 0;';
    fixture.style = 'height: 1000000000px';
```

**Comment by tbranyen** [comment]
Ohhhh you've dropped the unit with:

``` js
    HyperList.mergeStyle(fixture, {height: 1e9})
```

I wonder if that's why.

**Comment by tbranyen** [comment]
Fixed in #9850074

**Comment by soyuka** [comment]
Hmm yeah just tried to put units back again but still have the issue.

**Comment by tbranyen** [comment]
Did you rebuild? I'm pretty sure this is the problem since you can't have unit less heights.

```
$0.style.height = 100000
100000
$0.style.height
"100px"
$0.style.height = `1000px`
"1000px"
$0.style.height
"1000px"
```

**Comment by soyuka** [comment]
Yeah I rebuilded but weird still the error. Anyway sorry about that I shouldn't have dropped the units in the first place. We can still revert #19.

Oh just noticed you merged everything! Never mind :).

**Comment by tbranyen** [comment]
That is weird that you see the warning, since it's only a `console.warn` I wouldn't worry too much about it haha.

**Comment by soyuka** [comment]
Haha yes I know, can you still confirm that you have that same warning on firefox (or maybe the thing is cached but I doubt it)? The warning is gone on chrome anyway!

**Comment by tbranyen** [comment]
Urgh I see it in Firefox... reopening.

**Comment by soyuka** [comment]
Haha okay debugged it, nothing to do with mergeStyle. Patching.

**Comment by tbranyen** [comment]
:+1:

**Comment by tbranyen** [comment]
Confirmed the fix: `HyperList: The maximum element height 10000000px has been exceeded; please reduce your item height.`
